//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CARA_Draftv0._1
{
    using System;
    using System.Collections.Generic;
    
    public partial class CA_USUARIO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CA_USUARIO()
        {
            this.CA_USUARIO_CENTRO = new HashSet<CA_USUARIO_CENTRO>();
        }
    
        public string PK_Usuario { get; set; }
        public string NB_Primero { get; set; }
        public string NB_Segundo { get; set; }
        public string AP_Primero { get; set; }
        public string AP_Segundo { get; set; }
        public string Tel_Celular { get; set; }
        public string Tel_Trabajo { get; set; }
        public bool Active { get; set; }
        public bool PasswordChanged { get; set; }
        public string Email { get; set; }
        public bool EmailConfirmed { get; set; }
        public string PasswordHash { get; set; }
        public string SecurityStamp { get; set; }
        public string PhoneNumber { get; set; }
        public bool PhoneNumberConfirmed { get; set; }
        public bool TwoFactorEnabled { get; set; }
        public Nullable<System.DateTime> LockoutEndDateUtc { get; set; }
        public bool LockoutEnabled { get; set; }
        public int AccessFailedCount { get; set; }
        public string UserName { get; set; }
        public string ProfileImgPath { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CA_USUARIO_CENTRO> CA_USUARIO_CENTRO { get; set; }
    }
}
