//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CARA_Draftv0._1
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_CENTROS_ADMINISTRADORES
    {
        public int PK_Centro { get; set; }
        public string Centro { get; set; }
        public string ID_Proveedor { get; set; }
        public string Registrado { get; set; }
        public string Email { get; set; }
        public string Estatus { get; set; }
    }
}
