//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CARA_Draftv0._1
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_DSH_PERFILES
    {
        public int PK_Episodio { get; set; }
        public int PK_Perfil { get; set; }
        public int FK_Centro { get; set; }
        public string Centro { get; set; }
        public System.DateTime Fecha_Admisión { get; set; }
        public int ID_Paciente { get; set; }
        public string Tipo_Admisión { get; set; }
        public Nullable<int> Dias_en_Espera { get; set; }
        public int Arrestos_30_Dias { get; set; }
        public string Fuente_Referido { get; set; }
        public string Episodios_Previos { get; set; }
        public string Grupo_de_Apoyo { get; set; }
        public string Genero { get; set; }
        public string Estado_Marital { get; set; }
        public string Municipio { get; set; }
        public string Residencia { get; set; }
        public string Hijos_Menores { get; set; }
        public string Embarazada { get; set; }
        public string Veterano { get; set; }
        public string Escolaridad { get; set; }
        public string Condicion_Laboral { get; set; }
        public string Estudios { get; set; }
        public string Fuente_Ingreso { get; set; }
        public string Droga_Primaria { get; set; }
        public string Toxicologia_Primaria { get; set; }
        public string Via_Primaria { get; set; }
        public string Frecuencia_Primaria { get; set; }
        public int Edad_Primaria { get; set; }
        public string Droga_Secundaria { get; set; }
        public string Toxicologia_Secundaria { get; set; }
        public string Via_Secundaria { get; set; }
        public string Frecuencia_Secundaria { get; set; }
        public int Edad_Secundaria { get; set; }
        public string Droga_Terciaria { get; set; }
        public string Toxicologia_Terciaria { get; set; }
        public string Via_Terciaria { get; set; }
        public string Frecuencia_Terciaria { get; set; }
        public int Edad_Terciaria { get; set; }
        public string Droga_Cuarta { get; set; }
        public string Toxicologia_Cuarta { get; set; }
        public string Via_Cuarta { get; set; }
        public string Frecuencia_Cuarta { get; set; }
        public int Edad_Cuarta { get; set; }
        public string Droga_Quinta { get; set; }
        public string Toxicologia_Quinta { get; set; }
        public string Via_Quinta { get; set; }
        public string Frecuencia_Quinta { get; set; }
        public int Edad_Quinta { get; set; }
        public string Evento_Sobredosis { get; set; }
        public string Sobredosis_Primaria { get; set; }
        public string Sobredosis_Secundaria { get; set; }
        public string Sobredosis_Terciaria { get; set; }
        public string Sobredosis_Cuarta { get; set; }
        public string ICDX_Primaria { get; set; }
        public string ICDX_Secundaria { get; set; }
        public string ICDX_Terciaria { get; set; }
        public string ICDX_Cuarta { get; set; }
        public string DSMV_Primaria { get; set; }
        public string DSMV_Secundaria { get; set; }
        public string DSMV_Terciaria { get; set; }
        public string DSMV_Cuarta { get; set; }
        public string Condicion_Primaria { get; set; }
        public string Condicion_Secundaria { get; set; }
        public string Condicion_Terciaria { get; set; }
        public string Condicion_Cuarta { get; set; }
        public string Nivel_Cuidado { get; set; }
        public string Seguro_Salud { get; set; }
    }
}
