//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CARA_Draftv0._1
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_DSH_PLN_ViaSustancia
    {
        public int PK_Perfil { get; set; }
        public string DE_ViaSustancia { get; set; }
        public System.DateTime FE_Perfil { get; set; }
        public int FK_Genero { get; set; }
        public int FK_ViaSustancia { get; set; }
        public int FK_NivelSustancia { get; set; }
        public int FK_Centro { get; set; }
    }
}
