//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CARA_Draftv0._1
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_LISTA_USUARIOS_ASSMCA
    {
        public string PK_Usuario { get; set; }
        public string Nombre { get; set; }
        public string Email { get; set; }
        public string Tel_Celular { get; set; }
        public string Rol { get; set; }
        public string PK_Roles { get; set; }
        public string Confirmado { get; set; }
        public string Estatus { get; set; }
        public bool Active { get; set; }
        public string Imagen_Perfil { get; set; }
        public string Accesos { get; set; }
    }
}
