//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CARA_Draftv0._1
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_USUARIOS_CENTROS_LICENCIAS
    {
        public string PK_Usuario { get; set; }
        public string NombreUsuario { get; set; }
        public string Email { get; set; }
        public string PK_Roles { get; set; }
        public string Name { get; set; }
        public string UsuarioEstatus { get; set; }
        public int PK_Centro { get; set; }
        public string NB_Centro { get; set; }
        public string CentroEstatus { get; set; }
        public int PK_Licencia { get; set; }
        public string NB_Licencia { get; set; }
        public string NB_Categoria { get; set; }
        public int PK_Centro_Licencia { get; set; }
        public string NR_Licencia { get; set; }
        public Nullable<System.DateTime> FE_Expiracion { get; set; }
        public string CentroLicenciaEstatus { get; set; }
    }
}
